### PR TITLE
Ignored for a reason

### PR DESCRIPTION
**Pull request by jaybosamiya**
This PR adds support for inline reasons to ignoring an example, to aid in quickly grepping and figuring out why an example file was ignored.

Via a quick `for i in $(rg ignore -l | grep .rs); do git blame "$i" | head -1 ; done`, I'm just pinging the folks who had ignored all the currently ignored files in `source/rust_verify/example/` so that you can update with the reasons for a file being ignored (or change it to unignored if it should not be):
+ ~~@parno~~
+ ~~@tjhance~~
+ @jonhnet 
+ ~~@utaal~~ Done as example 

As an example of a comment, I've already gone ahead and added the comment to the `bitvector_garbage` file that was ignored a few months ago as part of the z3 upgrade in e406a6a2af7c04731d99690d892f158fdea82656

Once all the ignored examples are accounted for, we _could_ change it such that any ignored file without a reason will complain about not having a reason associated, but I have not included any such code just yet. If at least one other person believes this would be useful, I'm happy to add that code once all ignored ones have a comment associated.

Setting this PR as a draft until relevant ignores from folks above are completed.

### CODE REVIEW

**Comment by utaal** [comment]
This looks great, thanks! Two comments: can we add a visual separator between ignore and the comment? And: can we make the comment required if an example is `ignore`?

**Review by utaal — APPROVED** [review]
TYVM.

**Comment by jaybosamiya** [comment]
Just a gentle ping to add reasons for the ignored examples, so that we can switch over ignored reasons as being required, and merge this into `main`

@tjhance:
```
state_machines/cyclic_buffer.rs --- b11b2cc52 (Travis Hance 2022-08-19 10:10:11 -0400   1) // rust_verify/tests/example.rs ignore
state_machines/tutorial/fifo.rs --- e3669fabd source/rust_verify/example/state_machines/tutorial/fifo.rs (Travis Hance     2022-08-09 14:52:48 -0400   1) // rust_verify/tests/example.rs ignore
state_machines/tutorial/unverified_counting_to_2.rs --- 234e7146e (Travis Hance 2022-04-29 20:07:45 -0400  1) // rust_verify/tests/example.rs ignore
state_machines/tutorial/unverified_counting_to_n.rs --- c4477686a (Travis Hance 2022-05-20 13:54:34 -0400  1) // rust_verify/tests/example.rs ignore
state_machines/tutorial/unverified_fifo.rs --- 234e7146e (Travis Hance                 2022-04-29 20:07:45 -0400   1) // rust_verify/tests/example.rs ignore
state_machines/tutorial/unverified_rc.rs --- 7bbbd668a (Travis Hance 2023-01-02 21:01:21 -0500  1) // rust_verify/tests/example.rs ignore
state_machines/disk_example.rs --- 3db980a5a (Travis Hance    2022-07-29 14:20:01 -0400   1) // rust_verify/tests/example.rs ignore
state_machines/unbounded_log.rs --- cb4f9a2f3 (Travis Hance    2022-07-01 11:07:42 -0400    1) // rust_verify/tests/example.rs ignore
```

@jonhnet:
```
scache/rwlock.rs --- 3bfbf819c (Jon Howell 2023-01-04 13:36:20 -0800    1) // rust_verify/tests/example.rs ignore
```

**Comment by tjhance** [comment]
i added some reasons. the FIFO example is un-ignored in the main_new branch. I also deleted a couple of files because they are now in verus-systems-code.

**Pull request merged**
