### PR TITLE
Move View for Vec and add feature = "allocator"

### PR DESCRIPTION
**Pull request by Chris-Hawblitzel**
This is a fix for https://github.com/verus-lang/verus/issues/1137 .  The fix looked straightforward initially: we just have to move the declaration of View for Vec out of std_specs (where it gets erased during an ordinary rustc build) and into view.rs, where it is kept in all builds.  However, Vec is generic over Allocator, and we can't express this without using feature(allocator_api).  I didn't want to add feature(allocator_api) to all vstd builds, but some people might want the version that is generic over Allocator, so I added another feature flag `feature = "allocator"` to control this.

### CODE REVIEW

**Comment by utaal** [comment]
How does one set this new `feature = "allocator"`? Do we need to add it to `vargo`?

**Comment by Chris-Hawblitzel** [comment]
> How does one set this new `feature = "allocator"`? Do we need to add it to `vargo`?

For vargo, we've already got `verus_keep_ghost` enabled, so hopefully `allocator` won't matter in this case.  Mainly, `allocator` is for direct compilation with cargo/rustc when `verus_keep_ghost` is false.

**Comment by utaal** [comment]
Can we document it somewhere? (I realize we may be also missing docs for `alloc` and `std`).

**Comment by Chris-Hawblitzel** [comment]
> Can we document this feature somewhere? (I realize we may be also missing docs for `alloc` and `std`).

I added a discussion for this here: https://github.com/verus-lang/verus/discussions/1162

**Review by utaal — APPROVED** [review]

**Pull request merged**
