### PR TITLE
Add a simplified version of the quantifier instantiation profiler (--use-internal-profiler)

### PR DESCRIPTION
**Pull request by utaal**
It only counts instantiations, and reports counts for builtin/internal quantifiers.

It is intended, mainly, to find potential issues with internal quantifiers, not as a tool for the end user.

Sample output:

```
note:  1. Quantifier constructor_accessor_axiom, instantiations: 144041
          at: datatype#225, instantiations: 31253
          at: datatype#63, instantiations: 14099
          at: datatype#54, instantiations: 14099
          at: datatype#57, instantiations: 14099
          at: datatype#60, instantiations: 14099
          at: datatype#235, instantiations: 8070
          at: datatype#232, instantiations: 8070
          at: datatype#21, instantiations: 3790
          at: datatype#216, instantiations: 2628
          at: datatype#219, instantiations: 2628
          at: datatype#138, instantiations: 1673
          at: datatype#126, instantiations: 1673
          at: datatype#144, instantiations: 1673
          at: datatype#135, instantiations: 1673
          at: datatype#141, instantiations: 1673
          at: datatype#147, instantiations: 1673
          at: datatype#129, instantiations: 1673
          at: datatype#132, instantiations: 1673
          at: datatype#69, instantiations: 1649
          at: datatype#96, instantiations: 1319
          at: datatype#99, instantiations: 1319
          at: datatype#93, instantiations: 1319
          at: datatype#203, instantiations: 1180
          at: datatype#200, instantiations: 1180
          at: datatype#36, instantiations: 1126
          at: datatype#39, instantiations: 1126
          at: datatype#42, instantiations: 1126
          at: datatype#45, instantiations: 1126
          at: datatype#27, instantiations: 692
          at: datatype#82, instantiations: 348
          at: datatype#85, instantiations: 348
          at: datatype#193, instantiations: 270
          at: datatype#163, instantiations: 270
          at: datatype#181, instantiations: 270
          at: datatype#187, instantiations: 270
          at: datatype#190, instantiations: 270
          at: datatype#178, instantiations: 270
          at: datatype#175, instantiations: 270
          at: datatype#169, instantiations: 270
          at: datatype#184, instantiations: 270
          at: datatype#172, instantiations: 270
          at: datatype#166, instantiations: 270
          at: datatype#75, instantiations: 261
          at: datatype#15, instantiations: 168
          at: datatype#209, instantiations: 164
          at: datatype#110, instantiations: 79
          at: datatype#113, instantiations: 79
          at: datatype#107, instantiations: 79
          at: datatype#255, instantiations: 73
          at: datatype#252, instantiations: 73
          at: datatype#242, instantiations: 9
          at: datatype#245, instantiations: 9

note:  2. Quantifier prelude_u_clip, instantiations: 9315
          at: #9430!2, instantiations: 9315

note:  3. Quantifier prelude_unbox_box_bool, instantiations: 8348
          at: #62, instantiations: 8348

note:  4. Quantifier prelude_unbox_box_int, instantiations: 6871
          at: #68, instantiations: 6871

note:  5. Quantifier internal_pervasive.seq.Seq.index.?_pre_post_definition, instantiations: 5850
          at: #9587!3, instantiations: 5850

note:  6. Quantifier prelude_nat_clip, instantiations: 5063
          at: #10394!2, instantiations: 5063

note:  7. Quantifier prelude_box_unbox_int, instantiations: 3221
          at: #90!1, instantiations: 3221

[...]

note: 19. Quantifier user_crate__aux_defs__Arch__inv_57, instantiations: 1286
          at: #32797!6, instantiations: 532
          at: #21116!1, instantiations: 243
          at: #23942!1, instantiations: 243
          at: #63864!1, instantiations: 114
          at: #64985!1, instantiations: 73
          at: #62422!1, instantiations: 57
          at: #39736!1, instantiations: 22
          at: #37492!1, instantiations: 2
   --> verified-nrkernel/page-table/aux_defs.rs:313:24
    |
311 |           &&& self.layers.len() <= MAX_NUM_LAYERS
    |  _____________-
312 | |         &&& forall|i:nat|
313 | |             #![trigger self.entry_size(i)]
    | |                        ^^^^^^^^^^^^^^^^^^
314 | |             #![trigger self.num_entries(i)]
    | |                        ^^^^^^^^^^^^^^^^^^^
...   |
318 | |                 &&& self.entry_size_is_next_layer_size(i)
319 | |             }
    | |_____________- Triggers selected for this quantifier

note: 20. Quantifier internal_crate__pt_impl__l2_impl__GhostPageDirectoryEntry_box_axiom_definition, instantiations: 1281
          at: #1351, instantiations: 1281
```

### CODE REVIEW

**Comment by parno** [comment]
Can you say a bit more about your goals for this mode?  In other words, what should the Verus-internal developer learn from the output?

If we just want to see the impact of internal quantifiers, we could potentially remove or negate this line:
https://github.com/secure-foundations/verus/blob/51cda618fb61626440e8558594040873e73c6916/source/air/src/profiler.rs#L49
Then all of the existing profiler code would continue to work.  We'd probably want to update the results display, however, so that internal quantifiers don't try to print a span.

**Comment by Chris-Hawblitzel** [comment]
Is there any way to get the datatype names?  It's hard to know what to make of `at: datatype#225, instantiations: 31253`.

**Comment by utaal** [comment]
> Is there any way to get the datatype names? It's hard to know what to make of `at: datatype#225, instantiations: 31253`.

Maybe. `constructor_accessor_axiom` quantifier definitions are logged by https://github.com/Z3Prover/z3/blob/5a9b0dd747a2fc26513fcb15181678781e6667a7/src/ast/datatype_decl_plugin.cpp#L538-L539 and `family_name` I believe is the internal name of the datatype. Unfortunately it appears they get renamed:

_z3 trace_
```
[mk-quant] datatype#6 constructor_accessor_axiom 2 datatype#3 datatype#5
```
but it may be possible to reconstruct it from things like:

_z3 trace_
```
[mk-app] datatype#11 pervasive.option.Option./Some datatype#10
[mk-app] datatype#12 pattern datatype#11
[mk-app] datatype#13 pervasive.option.Option./Some/?_0 datatype#11
```

or we may be able to change the datatype plugin's code to output more descriptive names.

**Comment by parno** [comment]
Thanks for the additional background on the motivation for this addition.  For myself, I would tend not to show details that are not readily interpretable, so I would be inclined to omit things like `datatype#225, instantiations: 31253` until we can figure out how to show something semantically meaningful, but if you find it useful, we can certainly keep it. 

We can also look into improving the main profiler's speed, which I think mainly comes down to telling z3tracer to track less information.  At least initially, I didn't want to turn off too much, in case it became useful later, but we could shift to a slimmed down mode now, if the current version is too slow to be useful.

For raw count vs. cost, I think both can be useful, even internally, so perhaps we should add an option to `--profile` to let the user select which one they want to sort by?

**Comment by utaal** [comment]
We'll reconsider this.

**Pull request closed without merging**
