### PR TITLE
Use a separate ADT node, and generalised traits to support array, slice

### PR DESCRIPTION
**Pull request by utaal**
Candidate replacement for https://github.com/verus-lang/verus/pull/390 

Blocked behind some version of https://github.com/verus-lang/verus/pull/327

### CODE REVIEW

**Comment by jaybosamiya** [comment]
Just adding a note here that once this is merged, we should be able to switch the [`bytes` module](https://github.com/verus-lang/verus/blob/main/source/pervasive/bytes.rs) (introduced in #453) to be more precise, and not require the otherwise-unnecessary `Vec` allocation

**Comment by utaal** [comment]
I'm going to revive this, now that #571 has landed.

**Comment by utaal** [comment]
I'm going to revive this, now that #571 has landed. cc/ @tjhance

**Comment by utaal** [comment]
Replaced by #611.
(Please don't delete the branch for the time being, as this contains the diff for the first attempt.)

**Pull request closed without merging**
